import typing
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

# Each UI has two classes: one that defines the graphics (suffix _window) and one that defines the controls that make it a GUI (suffix _gui)

class add_job_window(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(719, 611)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 591, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Add_material_button = QtWidgets.QPushButton(self.layoutWidget)
        self.Add_material_button.setObjectName("Add_material_button")
        self.gridLayout_5.addWidget(self.Add_material_button, 0, 2, 2, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_5.addWidget(self.buttonBox, 5, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 2, 1, 1)
        self.Solvent_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.Solvent_comboBox.setObjectName("Solvent_comboBox")
        self.gridLayout_2.addWidget(self.Solvent_comboBox, 2, 0, 1, 1)
        self.Salt_comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.Salt_comboBox_4.setObjectName("Salt_comboBox_4")
        self.gridLayout_2.addWidget(self.Salt_comboBox_4, 2, 1, 1, 1)
        self.selectSaltConc = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.selectSaltConc.setDecimals(2)
        self.selectSaltConc.setSingleStep(0.01)
        self.selectSaltConc.setObjectName("selectSaltConc")
        self.gridLayout_2.addWidget(self.selectSaltConc, 2, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.PE_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.PE_comboBox.setObjectName("PE_comboBox")
        self.gridLayout.addWidget(self.PE_comboBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.NE_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.NE_comboBox.setObjectName("NE_comboBox")
        self.gridLayout.addWidget(self.NE_comboBox, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Del_button = QtWidgets.QPushButton(self.layoutWidget)
        self.Del_button.setObjectName("Del_button")
        self.gridLayout_4.addWidget(self.Del_button, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 4, 1, 1)
        self.Add_button = QtWidgets.QPushButton(self.layoutWidget)
        self.Add_button.setObjectName("Add_button")
        self.gridLayout_4.addWidget(self.Add_button, 0, 0, 1, 1)
        self.Edit_button = QtWidgets.QPushButton(self.layoutWidget)
        self.Edit_button.setObjectName("Edit_button")
        self.gridLayout_4.addWidget(self.Edit_button, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 4, 0, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.gridLayout_5.addLayout(self.verticalLayout, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Add_material_button.setText(_translate("Dialog", "Add Material"))
        self.label_3.setText(_translate("Dialog", "Electrolyte Composition"))
        self.label_4.setText(_translate("Dialog", "Solvent"))
        self.label_5.setText(_translate("Dialog", "Salt"))
        self.label_6.setText(_translate("Dialog", "Salt Concentration [m]"))
        self.label.setText(_translate("Dialog", "Positive Electrode"))
        self.label_2.setText(_translate("Dialog", "Negative Electrode"))
        self.label_8.setText(_translate("Dialog", "Add Job"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Material_ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Concentration"))
        self.label_7.setText(_translate("Dialog", "Additives"))
        self.Del_button.setText(_translate("Dialog", "Delete"))
        self.Add_button.setText(_translate("Dialog", "Add"))
        self.Edit_button.setText(_translate("Dialog", "Edit"))
        self.label_9.setText(_translate("Dialog", "Replicates"))

class additive_window(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(466, 136)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 90, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 22, 361, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Name_label = QtWidgets.QLabel(self.layoutWidget)
        self.Name_label.setObjectName("Name_label")
        self.gridLayout.addWidget(self.Name_label, 0, 0, 1, 1)
        self.Conc_label = QtWidgets.QLabel(self.layoutWidget)
        self.Conc_label.setObjectName("Conc_label")
        self.gridLayout.addWidget(self.Conc_label, 0, 1, 1, 1)
        self.selectAdditive = QtWidgets.QComboBox(self.layoutWidget)
        self.selectAdditive.setObjectName("selectAdditive")
        self.gridLayout.addWidget(self.selectAdditive, 1, 0, 1, 1)
        self.selectConc = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.selectConc.setObjectName("selectConc")
        self.selectConc.setSingleStep(0.01)
        self.selectConc.setDecimals(2)
        self.gridLayout.addWidget(self.selectConc, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Name_label.setText(_translate("Dialog", "Additive"))
        self.Conc_label.setText(_translate("Dialog", "Additive Concentration"))

class additive_error_window(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(210, 178)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 141, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Additive already exists or 0 Concentration was entered, please use the Edit button to edit the existing additive or try again."))
        self.pushButton.setText(_translate("Dialog", "OK"))

class new_material_window(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(580, 174)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 140, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 526, 99))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.molarmass = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.molarmass.setObjectName("molarmass")
        self.molarmass.setMaximum(999.999)
        self.gridLayout.addWidget(self.molarmass, 3, 1, 1, 1)
        self.ID = QtWidgets.QLabel(self.layoutWidget)
        self.ID.setAlignment(QtCore.Qt.AlignCenter)
        self.ID.setWordWrap(True)
        self.ID.setObjectName("ID")
        self.gridLayout.addWidget(self.ID, 0, 0, 1, 1)
        self.Name = QtWidgets.QLabel(self.layoutWidget)
        self.Name.setObjectName("Name")
        self.gridLayout.addWidget(self.Name, 0, 1, 1, 1)
        self.dateObt = QtWidgets.QLabel(self.layoutWidget)
        self.dateObt.setObjectName("dateObt")
        self.gridLayout.addWidget(self.dateObt, 0, 3, 1, 1)
        self.ID_box = QtWidgets.QLineEdit(self.layoutWidget)
        self.ID_box.setEnabled(False)
        self.ID_box.setText("")
        self.ID_box.setAlignment(QtCore.Qt.AlignCenter)
        self.ID_box.setReadOnly(True)
        self.ID_box.setObjectName("ID_box")
        self.gridLayout.addWidget(self.ID_box, 1, 0, 1, 1)
        self.Supplier = QtWidgets.QLabel(self.layoutWidget)
        self.Supplier.setObjectName("Supplier")
        self.gridLayout.addWidget(self.Supplier, 0, 2, 1, 1)
        self.date_box = QtWidgets.QDateEdit(self.layoutWidget)
        self.date_box.setObjectName("date_box")
        self.gridLayout.addWidget(self.date_box, 1, 3, 1, 1)
        self.Name_box = QtWidgets.QLineEdit(self.layoutWidget)
        self.Name_box.setEnabled(True)
        self.Name_box.setObjectName("Name_box")
        self.gridLayout.addWidget(self.Name_box, 1, 1, 1, 1)
        self.Supplier_box = QtWidgets.QLineEdit(self.layoutWidget)
        self.Supplier_box.setText("")
        self.Supplier_box.setObjectName("Supplier_box")
        self.gridLayout.addWidget(self.Supplier_box, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ID.setText(_translate("Dialog", "Material ID"))
        self.Name.setText(_translate("Dialog", "Chemical Name"))
        self.dateObt.setText(_translate("Dialog", "Date Obtained"))
        self.Supplier.setText(_translate("Dialog", "Supplier"))
        self.label.setText(_translate("Dialog", "Molar Mass (g/mol)"))

class stockSolutions_window(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1234, 321)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(860, 280, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 70, 1192, 201))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_13.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_13.addWidget(self.label_18)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.solv_0_box = QtWidgets.QComboBox(self.widget)
        self.solv_0_box.setObjectName("solv_0_box")
        self.verticalLayout_12.addWidget(self.solv_0_box)
        self.comp_0_box = QtWidgets.QComboBox(self.widget)
        self.comp_0_box.setObjectName("comp_0_box")
        self.verticalLayout_12.addWidget(self.comp_0_box)
        self.conc_0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_0.setObjectName("conc_0")
        self.verticalLayout_12.addWidget(self.conc_0)
        self.volume_0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_0.setDecimals(0)
        self.volume_0.setMaximum(5999.0)
        self.volume_0.setObjectName("volume_0")
        self.verticalLayout_12.addWidget(self.volume_0)
        self.density_0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_0.setObjectName("density_0")
        self.verticalLayout_12.addWidget(self.density_0)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.solv_1_box = QtWidgets.QComboBox(self.widget)
        self.solv_1_box.setObjectName("solv_1_box")
        self.verticalLayout_11.addWidget(self.solv_1_box)
        self.comp_1_box = QtWidgets.QComboBox(self.widget)
        self.comp_1_box.setObjectName("comp_1_box")
        self.verticalLayout_11.addWidget(self.comp_1_box)
        self.conc_1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_1.setObjectName("conc_1")
        self.verticalLayout_11.addWidget(self.conc_1)
        self.volume_1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_1.setDecimals(0)
        self.volume_1.setMaximum(5999.0)
        self.volume_1.setObjectName("volume_1")
        self.verticalLayout_11.addWidget(self.volume_1)
        self.density_1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_1.setObjectName("density_1")
        self.verticalLayout_11.addWidget(self.density_1)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.solv_2_box = QtWidgets.QComboBox(self.widget)
        self.solv_2_box.setObjectName("solv_2_box")
        self.verticalLayout_10.addWidget(self.solv_2_box)
        self.comp_2_box = QtWidgets.QComboBox(self.widget)
        self.comp_2_box.setObjectName("comp_2_box")
        self.verticalLayout_10.addWidget(self.comp_2_box)
        self.conc_2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_2.setObjectName("conc_2")
        self.verticalLayout_10.addWidget(self.conc_2)
        self.volume_2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_2.setDecimals(0)
        self.volume_2.setMaximum(5999.0)
        self.volume_2.setObjectName("volume_2")
        self.verticalLayout_10.addWidget(self.volume_2)
        self.density_2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_2.setObjectName("density_2")
        self.verticalLayout_10.addWidget(self.density_2)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.solv_3_box = QtWidgets.QComboBox(self.widget)
        self.solv_3_box.setObjectName("solv_3_box")
        self.verticalLayout_9.addWidget(self.solv_3_box)
        self.comp_3_box = QtWidgets.QComboBox(self.widget)
        self.comp_3_box.setObjectName("comp_3_box")
        self.verticalLayout_9.addWidget(self.comp_3_box)
        self.conc_3 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_3.setObjectName("conc_3")
        self.verticalLayout_9.addWidget(self.conc_3)
        self.volume_3 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_3.setDecimals(0)
        self.volume_3.setMaximum(5999.0)
        self.volume_3.setObjectName("volume_3")
        self.verticalLayout_9.addWidget(self.volume_3)
        self.density_3 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_3.setObjectName("density_3")
        self.verticalLayout_9.addWidget(self.density_3)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.solv_4_box = QtWidgets.QComboBox(self.widget)
        self.solv_4_box.setObjectName("solv_4_box")
        self.verticalLayout_8.addWidget(self.solv_4_box)
        self.comp_4_box = QtWidgets.QComboBox(self.widget)
        self.comp_4_box.setObjectName("comp_4_box")
        self.verticalLayout_8.addWidget(self.comp_4_box)
        self.conc_4 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_4.setObjectName("conc_4")
        self.verticalLayout_8.addWidget(self.conc_4)
        self.volume_4 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_4.setDecimals(0)
        self.volume_4.setMaximum(5999.0)
        self.volume_4.setObjectName("volume_4")
        self.verticalLayout_8.addWidget(self.volume_4)
        self.density_4 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_4.setObjectName("density_4")
        self.verticalLayout_8.addWidget(self.density_4)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.line_9 = QtWidgets.QFrame(self.widget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout.addWidget(self.line_9)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.solv_5_box = QtWidgets.QComboBox(self.widget)
        self.solv_5_box.setObjectName("solv_5_box")
        self.verticalLayout_7.addWidget(self.solv_5_box)
        self.comp_5_box = QtWidgets.QComboBox(self.widget)
        self.comp_5_box.setObjectName("comp_5_box")
        self.verticalLayout_7.addWidget(self.comp_5_box)
        self.conc_5 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_5.setObjectName("conc_5")
        self.verticalLayout_7.addWidget(self.conc_5)
        self.volume_5 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_5.setDecimals(0)
        self.volume_5.setMaximum(5999.0)
        self.volume_5.setObjectName("volume_5")
        self.verticalLayout_7.addWidget(self.volume_5)
        self.density_5 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_5.setObjectName("density_5")
        self.verticalLayout_7.addWidget(self.density_5)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.line_10 = QtWidgets.QFrame(self.widget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout.addWidget(self.line_10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.solv_6_box = QtWidgets.QComboBox(self.widget)
        self.solv_6_box.setObjectName("solv_6_box")
        self.verticalLayout_6.addWidget(self.solv_6_box)
        self.comp_6_box = QtWidgets.QComboBox(self.widget)
        self.comp_6_box.setObjectName("comp_6_box")
        self.verticalLayout_6.addWidget(self.comp_6_box)
        self.conc_6 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_6.setObjectName("conc_6")
        self.verticalLayout_6.addWidget(self.conc_6)
        self.volume_6 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_6.setDecimals(0)
        self.volume_6.setMaximum(5999.0)
        self.volume_6.setObjectName("volume_6")
        self.verticalLayout_6.addWidget(self.volume_6)
        self.density_6 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_6.setObjectName("density_6")
        self.verticalLayout_6.addWidget(self.density_6)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.line_8 = QtWidgets.QFrame(self.widget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout.addWidget(self.line_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.solv_7_box = QtWidgets.QComboBox(self.widget)
        self.solv_7_box.setObjectName("solv_7_box")
        self.verticalLayout_5.addWidget(self.solv_7_box)
        self.comp_7_box = QtWidgets.QComboBox(self.widget)
        self.comp_7_box.setObjectName("comp_7_box")
        self.verticalLayout_5.addWidget(self.comp_7_box)
        self.conc_7 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_7.setObjectName("conc_7")
        self.verticalLayout_5.addWidget(self.conc_7)
        self.volume_7 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_7.setDecimals(0)
        self.volume_7.setMaximum(5999.0)
        self.volume_7.setObjectName("volume_7")
        self.verticalLayout_5.addWidget(self.volume_7)
        self.density_7 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_7.setObjectName("density_7")
        self.verticalLayout_5.addWidget(self.density_7)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.line_7 = QtWidgets.QFrame(self.widget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout.addWidget(self.line_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.solv_8_box = QtWidgets.QComboBox(self.widget)
        self.solv_8_box.setObjectName("solv_8_box")
        self.verticalLayout_4.addWidget(self.solv_8_box)
        self.comp_8_box = QtWidgets.QComboBox(self.widget)
        self.comp_8_box.setObjectName("comp_8_box")
        self.verticalLayout_4.addWidget(self.comp_8_box)
        self.conc_8 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_8.setObjectName("conc_8")
        self.verticalLayout_4.addWidget(self.conc_8)
        self.volume_8 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_8.setDecimals(0)
        self.volume_8.setMaximum(5999.0)
        self.volume_8.setObjectName("volume_8")
        self.verticalLayout_4.addWidget(self.volume_8)
        self.density_8 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_8.setObjectName("density_8")
        self.verticalLayout_4.addWidget(self.density_8)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.solv_9_box = QtWidgets.QComboBox(self.widget)
        self.solv_9_box.setObjectName("solv_9_box")
        self.verticalLayout_3.addWidget(self.solv_9_box)
        self.comp_9_box = QtWidgets.QComboBox(self.widget)
        self.comp_9_box.setObjectName("comp_9_box")
        self.verticalLayout_3.addWidget(self.comp_9_box)
        self.conc_9 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_9.setObjectName("conc_9")
        self.verticalLayout_3.addWidget(self.conc_9)
        self.volume_9 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_9.setDecimals(0)
        self.volume_9.setMaximum(5999.0)
        self.volume_9.setObjectName("volume_9")
        self.verticalLayout_3.addWidget(self.volume_9)
        self.density_9 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_9.setObjectName("density_9")
        self.verticalLayout_3.addWidget(self.density_9)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_14 = QtWidgets.QFrame(self.widget)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout.addWidget(self.line_14)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.solv_10_box = QtWidgets.QComboBox(self.widget)
        self.solv_10_box.setObjectName("solv_10_box")
        self.verticalLayout_2.addWidget(self.solv_10_box)
        self.comp_10_box = QtWidgets.QComboBox(self.widget)
        self.comp_10_box.setObjectName("comp_10_box")
        self.verticalLayout_2.addWidget(self.comp_10_box)
        self.conc_10 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_10.setObjectName("conc_10")
        self.verticalLayout_2.addWidget(self.conc_10)
        self.volume_10 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_10.setDecimals(0)
        self.volume_10.setMaximum(5999.0)
        self.volume_10.setObjectName("volume_10")
        self.verticalLayout_2.addWidget(self.volume_10)
        self.density_10 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_10.setObjectName("density_10")
        self.verticalLayout_2.addWidget(self.density_10)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_15 = QtWidgets.QFrame(self.widget)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.horizontalLayout.addWidget(self.line_15)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.solv_11_box = QtWidgets.QComboBox(self.widget)
        self.solv_11_box.setObjectName("solv_11_box")
        self.verticalLayout.addWidget(self.solv_11_box)
        self.comp_11_box = QtWidgets.QComboBox(self.widget)
        self.comp_11_box.setObjectName("comp_11_box")
        self.verticalLayout.addWidget(self.comp_11_box)
        self.conc_11 = QtWidgets.QDoubleSpinBox(self.widget)
        self.conc_11.setObjectName("conc_11")
        self.verticalLayout.addWidget(self.conc_11)
        self.volume_11 = QtWidgets.QDoubleSpinBox(self.widget)
        self.volume_11.setDecimals(0)
        self.volume_11.setMaximum(5999.0)
        self.volume_11.setObjectName("volume_11")
        self.verticalLayout.addWidget(self.volume_11)
        self.density_11 = QtWidgets.QDoubleSpinBox(self.widget)
        self.density_11.setObjectName("density_11")
        self.verticalLayout.addWidget(self.density_11)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_13.setText(_translate("Dialog", "Stock Solutions"))
        self.label_14.setText(_translate("Dialog", "Solvent"))
        self.label_15.setText(_translate("Dialog", "Component"))
        self.label_16.setText(_translate("Dialog", "Component Conc (m)"))
        self.label_17.setText(_translate("Dialog", "Volume (uL)"))
        self.label_18.setText(_translate("Dialog", "Density (g/mL)"))
        self.label.setText(_translate("Dialog", "0"))
        self.label_2.setText(_translate("Dialog", "1"))
        self.label_3.setText(_translate("Dialog", "2"))
        self.label_4.setText(_translate("Dialog", "3"))
        self.label_10.setText(_translate("Dialog", "4"))
        self.label_7.setText(_translate("Dialog", "5"))
        self.label_6.setText(_translate("Dialog", "6"))
        self.label_8.setText(_translate("Dialog", "7"))
        self.label_5.setText(_translate("Dialog", "8"))
        self.label_12.setText(_translate("Dialog", "9"))
        self.label_11.setText(_translate("Dialog", "10"))
        self.label_9.setText(_translate("Dialog", "11"))

class new_material_gui(QtWidgets.QDialog):
    OKClicked = QtCore.pyqtSignal(str)
    def __init__(self, material_id):
        super().__init__()
        self.ui = new_material_window()
        self.ui.setupUi(self)
        self.ui.buttonBox.accepted.connect(self.new_mat_str)
        self.ui.ID_box.setText(str(material_id))
        self.ui.date_box.setDateTime(QtCore.QDateTime.currentDateTime())
        self.show()
    def collect_variables(self):
        return [int(self.ui.ID_box.text()), str(self.ui.Name_box.text()), str(self.ui.Supplier_box.text()), self.ui.molarmass.value(), self.ui.date_box.date().toPyDate()]
    def new_mat_str(self):
        self.OKClicked.emit(''.join(map(lambda x: str(x or '')+'|', self.collect_variables()[:-2]))[:-1])

class additive_gui(QtWidgets.QDialog):
    OKClicked = QtCore.pyqtSignal(str, float)
    def __init__(self, materials_list, set_name=None, set_conc=None):
        super().__init__()
        self.ui = additive_window()
        self.ui.setupUi(self)
        self.ui.buttonBox.accepted.connect(self.add_additive)
        self.ui.buttonBox.rejected.connect(self.reject)
        #combobox_strs = [''.join(map(lambda x: str(x or '')+'|', item[:-1]))[:-1] for item in materials_list]
        self.ui.selectAdditive.addItems(materials_list)
        if set_name:
            self.ui.selectAdditive.setCurrentIndex(self.ui.selectAdditive.findText(set_name))
        if set_conc:
            self.ui.selectConc.setValue(set_conc)
        self.show()
    def add_additive(self):
        self.OKClicked.emit(str(self.ui.selectAdditive.currentText()), self.ui.selectConc.value())
    
class additive_error_gui(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = additive_error_window()
        self.ui.setupUi(self)
        self.ui.pushButton.clicked.connect(self.accept)

class add_job_gui(QtWidgets.QDialog):
    def __init__(self, con):
        super().__init__()
        self.con = con
        self.ui = add_job_window()
        self.ui.setupUi(self)
        self.ui.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ui.buttonBox.accepted.connect(self.on_accepted)
        self.ui.buttonBox.rejected.connect(self.reject)
        self.ui.Add_material_button.clicked.connect(self.add_new_material)
        self.additive_list = []
        combobox_strs = self.get_material_list()
        self.ui.PE_comboBox.addItems(combobox_strs)
        self.ui.NE_comboBox.addItems(combobox_strs)
        self.ui.Solvent_comboBox.addItems(combobox_strs)
        self.ui.Salt_comboBox_4.addItems(combobox_strs)
        self.ui.PE_comboBox.setCurrentIndex(-1)
        self.ui.NE_comboBox.setCurrentIndex(-1)
        self.ui.Solvent_comboBox.setCurrentIndex(-1)
        self.ui.Salt_comboBox_4.setCurrentIndex(-1)
        self.ui.Add_button.clicked.connect(self.additive_to_table)
        self.ui.Edit_button.clicked.connect(self.edit_row)
        self.ui.Del_button.clicked.connect(self.delete_row)
        self.show()
    def get_material_list(self):
        materials_list = self.con.sql("SELECT * FROM Materials").fetchall()
        materials_list.sort(reverse=True)
        return [''.join(map(lambda x: str(x or '')+'|', item[:-2]))[:-1] for item in materials_list]
    def add_new_material(self):
        if self.con.execute("SELECT MAX(Material_ID) FROM Materials").fetchall()[0][0]:
            mat_id = self.con.execute("SELECT MAX(Material_ID) FROM Materials").fetchall()[0][0]+1
        else:
            mat_id = 1
        w = new_material_gui(mat_id)
        w.OKClicked.connect(self.update_selection)
        result = w.exec_()
        if result:
            self.con.execute("INSERT INTO Materials (Material_ID, Name, Supplier, molarMass, DateObtained) VALUES (?, ?, ?, ?, ?);", w.collect_variables())
    def update_selection(self, new_mat):
        self.ui.PE_comboBox.insertItem(0, new_mat)
        self.ui.NE_comboBox.insertItem(0, new_mat)
        self.ui.Solvent_comboBox.insertItem(0, new_mat)
        self.ui.Salt_comboBox_4.insertItem(0, new_mat)
    def additive_to_table(self):
        w = additive_gui(self.get_material_list())
        w.OKClicked.connect(self.additive_new_row)
        w.exec_()
    def additive_new_row(self, name, conc):
        if conc == 0.0:
            error_win = additive_error_gui()
            error_win.exec_()
            return
        mat_id, add_name, _ = name.split('|')
        for i in self.additive_list:
            if i[0] == int(mat_id):
                error_win = additive_error_gui()
                error_win.exec_()
                return 
        self.additive_list.append((int(mat_id), add_name, conc))
        self.ui.tableWidget.insertRow(self.ui.tableWidget.rowCount())
        self.ui.tableWidget.setItem(self.ui.tableWidget.rowCount()-1, 0, QtWidgets.QTableWidgetItem(mat_id))
        self.ui.tableWidget.setItem(self.ui.tableWidget.rowCount()-1, 1, QtWidgets.QTableWidgetItem(add_name))
        self.ui.tableWidget.setItem(self.ui.tableWidget.rowCount()-1, 2, QtWidgets.QTableWidgetItem(str(conc)))
    def edit_row(self):
        self.row_to_edit = self.ui.tableWidget.currentRow()
        combobox_strs = self.get_material_list()
        if self.row_to_edit == -1:
            return
        current_id = self.ui.tableWidget.item(self.row_to_edit, 0).text()
        current_conc = next(item[2] for item in self.additive_list if int(current_id) == item[0])
        current_name = next(s for s in combobox_strs if current_id == s.split('|')[0])
        w = additive_gui(combobox_strs, current_name, current_conc)
        w.OKClicked.connect(self.on_edit_row)
        w.exec_()
    def on_edit_row(self, name, conc):
        if conc == 0.0:
            error_win = additive_error_gui()
            error_win.exec_()
            return
        mat_id, add_name, _ = name.split('|')
        for i in [n for n in self.additive_list if n != self.additive_list[self.row_to_edit]]:
            if i[0] == int(mat_id):
                error_win = additive_error_gui()
                error_win.exec_()
                return
        self.additive_list[self.row_to_edit] = (int(mat_id), add_name, conc)
        self.ui.tableWidget.setItem(self.row_to_edit, 0, QtWidgets.QTableWidgetItem(mat_id))
        self.ui.tableWidget.setItem(self.row_to_edit, 1, QtWidgets.QTableWidgetItem(add_name))
        self.ui.tableWidget.setItem(self.row_to_edit, 2, QtWidgets.QTableWidgetItem(str(conc)))
    def delete_row(self):
        row_to_del = self.ui.tableWidget.currentRow()
        self.ui.tableWidget.takeItem(row_to_del, 0)
        self.ui.tableWidget.takeItem(row_to_del, 1)
        self.ui.tableWidget.takeItem(row_to_del, 2)
        for row in range(row_to_del, self.ui.tableWidget.rowCount()):
            self.ui.tableWidget.setItem(row, 0, self.ui.tableWidget.takeItem(row+1, 0))
            self.ui.tableWidget.setItem(row, 1, self.ui.tableWidget.takeItem(row+1, 1))
            self.ui.tableWidget.setItem(row, 2, self.ui.tableWidget.takeItem(row+1, 2))
        self.ui.tableWidget.setRowCount(self.ui.tableWidget.rowCount()-1)
        self.additive_list.pop(row_to_del)
    def on_accepted(self):
        solvent_mat_id, solvent_name, _ = self.ui.Solvent_comboBox.currentText().split('|')
        salt_mat_id, salt_name, _ = self.ui.Salt_comboBox_4.currentText().split('|')
        self.base_electrolyte = [solvent_mat_id, solvent_name, salt_mat_id, salt_name, self.ui.selectSaltConc.value()]
        self.electrodes = [self.ui.PE_comboBox.currentText().split('|')[0], self.ui.NE_comboBox.currentText().split('|')[0]]
    def outputs(self):
        return self.ui.spinBox.value(), self.electrodes, self.additive_list, self.base_electrolyte

class stock_solutions_gui(QtWidgets.QDialog):
    def __init__(self, con):
        super().__init__()
        self.con = con
        self.ui = stockSolutions_window()
        self.ui.setupUi(self)
        self.ui.buttonBox.accepted.connect(self.on_accept)
        self.ui.buttonBox.rejected.connect(self.reject)
        combobox_strs = self.get_material_list()
        combobox_strs.insert(0, 'None')
        self.ui.comp_0_box.addItems(combobox_strs)
        self.ui.comp_0_box.setCurrentIndex(0)
        self.ui.comp_1_box.addItems(combobox_strs)
        self.ui.comp_1_box.setCurrentIndex(0)
        self.ui.comp_2_box.addItems(combobox_strs)
        self.ui.comp_2_box.setCurrentIndex(0)
        self.ui.comp_3_box.addItems(combobox_strs)
        self.ui.comp_3_box.setCurrentIndex(0)
        self.ui.comp_4_box.addItems(combobox_strs)
        self.ui.comp_4_box.setCurrentIndex(0)
        self.ui.comp_5_box.addItems(combobox_strs)
        self.ui.comp_5_box.setCurrentIndex(0)
        self.ui.comp_6_box.addItems(combobox_strs)
        self.ui.comp_6_box.setCurrentIndex(0)
        self.ui.comp_7_box.addItems(combobox_strs)
        self.ui.comp_7_box.setCurrentIndex(0)
        self.ui.comp_8_box.addItems(combobox_strs)
        self.ui.comp_8_box.setCurrentIndex(0)
        self.ui.comp_9_box.addItems(combobox_strs)
        self.ui.comp_9_box.setCurrentIndex(0)
        self.ui.comp_10_box.addItems(combobox_strs)
        self.ui.comp_10_box.setCurrentIndex(0)
        self.ui.comp_11_box.addItems(combobox_strs)
        self.ui.comp_11_box.setCurrentIndex(0)
        self.ui.solv_0_box.addItems(combobox_strs)
        self.ui.solv_0_box.setCurrentIndex(0)
        self.ui.solv_1_box.addItems(combobox_strs)
        self.ui.solv_1_box.setCurrentIndex(0)
        self.ui.solv_2_box.addItems(combobox_strs)
        self.ui.solv_2_box.setCurrentIndex(0)
        self.ui.solv_3_box.addItems(combobox_strs)
        self.ui.solv_3_box.setCurrentIndex(0)
        self.ui.solv_4_box.addItems(combobox_strs)
        self.ui.solv_4_box.setCurrentIndex(0)
        self.ui.solv_5_box.addItems(combobox_strs)
        self.ui.solv_5_box.setCurrentIndex(0)
        self.ui.solv_6_box.addItems(combobox_strs)
        self.ui.solv_6_box.setCurrentIndex(0)
        self.ui.solv_7_box.addItems(combobox_strs)
        self.ui.solv_7_box.setCurrentIndex(0)
        self.ui.solv_8_box.addItems(combobox_strs)
        self.ui.solv_8_box.setCurrentIndex(0)
        self.ui.solv_9_box.addItems(combobox_strs)
        self.ui.solv_9_box.setCurrentIndex(0)
        self.ui.solv_10_box.addItems(combobox_strs)
        self.ui.solv_10_box.setCurrentIndex(0)
        self.ui.solv_11_box.addItems(combobox_strs)
        self.ui.solv_11_box.setCurrentIndex(0)
        self.stock_list = [[self.ui.solv_0_box, self.ui.comp_0_box, self.ui.conc_0, self.ui.volume_0, self.ui.density_0], 
                           [self.ui.solv_1_box, self.ui.comp_1_box, self.ui.conc_1, self.ui.volume_1, self.ui.density_1],
                           [self.ui.solv_2_box, self.ui.comp_2_box, self.ui.conc_2, self.ui.volume_2, self.ui.density_2],
                           [self.ui.solv_3_box, self.ui.comp_3_box, self.ui.conc_3, self.ui.volume_3, self.ui.density_3],
                           [self.ui.solv_4_box, self.ui.comp_4_box, self.ui.conc_4, self.ui.volume_4, self.ui.density_4],
                           [self.ui.solv_5_box, self.ui.comp_5_box, self.ui.conc_5, self.ui.volume_5, self.ui.density_5],
                           [self.ui.solv_6_box, self.ui.comp_6_box, self.ui.conc_6, self.ui.volume_6, self.ui.density_6],
                           [self.ui.solv_7_box, self.ui.comp_7_box, self.ui.conc_7, self.ui.volume_7, self.ui.density_7],
                           [self.ui.solv_8_box, self.ui.comp_8_box, self.ui.conc_8, self.ui.volume_8, self.ui.density_8],
                           [self.ui.solv_9_box, self.ui.comp_9_box, self.ui.conc_9, self.ui.volume_9, self.ui.density_9],
                           [self.ui.solv_10_box, self.ui.comp_10_box, self.ui.conc_10, self.ui.volume_10, self.ui.density_10],
                           [self.ui.solv_11_box, self.ui.comp_11_box, self.ui.conc_11, self.ui.volume_11, self.ui.density_11]]
        active_stock = self.con.sql("SELECT wellPosition, Solvent_Material_ID, Solvent_Name, Component1_Material_ID, Component1_Name, Component1_Conc_molal, Density_gmL, Volume_uL FROM stockSolutions").fetchall()
        if active_stock:
            for item in active_stock:
                well = item[0]
                solv_string = str(item[1])+'|'+item[2]
                if item[3]:
                    comp_string = str(item[3])+'|'+item[4]
                    self.stock_list[well][1].setCurrentIndex(self.stock_list[well][1].findText([i for i in combobox_strs if comp_string in i][0]))
                    self.stock_list[well][2].setValue(item[5])
                self.stock_list[well][0].setCurrentIndex(self.stock_list[well][0].findText([i for i in combobox_strs if solv_string in i][0]))
                self.stock_list[well][3].setValue(item[7])
                self.stock_list[well][4].setValue(item[6])

    def on_accept(self):
        self.con.sql("DROP TABLE StockSolutions")
        self.con.sql(r"""CREATE TABLE stockSolutions(
        wellPosition INTEGER,
        Solvent_Material_ID INTEGER,
        Solvent_Name VARCHAR(255),
        Component1_Material_ID INTEGER,
        Component1_Name VARCHAR(255), 
        Component1_Conc_molal DOUBLE,
        Density_gmL DOUBLE,
        Volume_uL DOUBLE)""")

        to_db = [[i, *str(OBjs[0].currentText()).split('|')[:2], *str(OBjs[1].currentText()).split('|')[:2], OBjs[2].value(), OBjs[4].value(), OBjs[3].value()] for i,OBjs in enumerate(self.stock_list) if str(OBjs[0].currentText()) != 'None']
        solutions_list = [i for i in to_db if len(i) == 8]
        solvents_list = [i[:3]+i[-2:] for i in to_db if len(i) == 7]
        if solutions_list:
            self.con.executemany("INSERT INTO StockSolutions(wellPosition, Solvent_Material_ID, Solvent_Name, Component1_Material_ID, Component1_Name, Component1_Conc_molal, Density_gmL, Volume_uL) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", solutions_list)
        if solvents_list:
            self.con.executemany("INSERT INTO StockSolutions(wellPosition, Solvent_Material_ID, Solvent_Name, Density_gmL, Volume_uL) VALUES (?, ?, ?, ?, ?)", solvents_list)
    def get_material_list(self):
        materials_list = self.con.sql("SELECT * FROM Materials").fetchall()
        materials_list.sort(reverse=True)
        return [''.join(map(lambda x: str(x or '')+'|', item[:-2]))[:-1] for item in materials_list]