name: CarSideImpact

parameters:
  x1: 
    bounds: [0.5, 1.5]
    type: range
  x2: 
    bounds: [0.45, 1.35]
    type: range
  x3: 
    bounds: [0.5, 1.5]
    type: range
  x4: 
    bounds: [0.5, 1.5]
    type: range
  x5: 
    bounds: [0.875, 2.625] 
    type: range
  x6: 
    bounds: [0.4, 1.2] 
    type: range
  x7: 
    bounds: [0.4, 1.2] 
    type: range

objectives:
  y1: 
    threshold: -45.4872
  y2: 
    threshold: -4.5114
  y3: 
    threshold: -13.3394
  y4: 
    threshold: -10.3942
  
  
  
   
  